# Default Theme

POWERTMUX_SEPARATOR_LEFT_BOLD="◀"
POWERTMUX_SEPARATOR_LEFT_THIN="❮"
POWERTMUX_SEPARATOR_RIGHT_BOLD="▶"
POWERTMUX_SEPARATOR_RIGHT_THIN="❯"

POWERTMUX_DEFAULT_BACKGROUND_COLOR=${POWERTMUX_DEFAULT_BACKGROUND_COLOR:-'236'}
POWERTMUX_DEFAULT_FOREGROUND_COLOR=${POWERTMUX_DEFAULT_FOREGROUND_COLOR:-'255'}

POWERTMUX_DEFAULT_LEFTSIDE_SEPARATOR=${POWERTMUX_DEFAULT_LEFTSIDE_SEPARATOR:-$POWERTMUX_SEPARATOR_RIGHT_BOLD}
POWERTMUX_DEFAULT_RIGHTSIDE_SEPARATOR=${POWERTMUX_DEFAULT_RIGHTSIDE_SEPARATOR:-$POWERTMUX_SEPARATOR_LEFT_BOLD}


# Format: plugin_name background_color foreground_color [non_default_separator]
if [ -z $POWERTMUX_LEFT_STATUS_PLUGINS ]; then
  POWERTMUX_LEFT_STATUS_PLUGINS=(
    "tmux_session_info 252 0" \
    "hostname 239 255" \
  )
fi

if [ -z $POWERTMUX_RIGHT_STATUS_PLUGINS ]; then
  POWERTMUX_RIGHT_STATUS_PLUGINS=(
    "lan_ip 239 255" \
    "wan_ip 239 255 ${POWERTMUX_SEPARATOR_LEFT_THIN}" \
    "battery 137 127" \
    "datetime 252 0" \
  )
fi
